/* Generated by Antigravity CLI 1.1.22 (Gemini 3.7 Flash (High)) */

/*
 * Copyright (C) 2026 Neverball authors
 *
 * NEVERBALL is  free software; you can redistribute  it and/or modify
 * it under the  terms of the GNU General  Public License as published
 * by the Free  Software Foundation; either version 2  of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT  ANY  WARRANTY;  without   even  the  implied  warranty  of
 * MERCHANTABILITY or  FITNESS FOR A PARTICULAR PURPOSE.   See the GNU
 * General Public License for more details.
 */

#ifndef ST_GAME_LINK_H
#define ST_GAME_LINK_H 1

#include "state.h"

extern struct state st_game_link;

int game_link_handle(const char *link);

#endif
