/* Generated by Antigravity CLI 1.1.22 (Gemini 3.7 Flash (High)) */

/*
 * Copyright (C) 2026 Neverball authors
 *
 * NEVERBALL is  free software; you can redistribute  it and/or modify
 * it under the  terms of the GNU General  Public License as published
 * by the Free  Software Foundation; either version 2  of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT  ANY  WARRANTY;  without   even  the  implied  warranty  of
 * MERCHANTABILITY or  FITNESS FOR A PARTICULAR PURPOSE.   See the GNU
 * General Public License for more details.
 */

#include <stdio.h>
#include <string.h>

#include "gui.h"
#include "transition.h"
#include "audio.h"
#include "config.h"
#include "common.h"
#include "package.h"
#include "set.h"
#include "progress.h"
#include "lang.h"
#include "log.h"
#include "video.h"
#include "geom.h"
#include "text.h"
#include "strbuf/strbuf.h"
#include "strbuf/substr.h"
#include "strbuf/joinstr.h"

#include "game_client.h"

#include "st_game_link.h"
#include "st_level.h"
#include "st_start.h"
#include "st_title.h"
#include "st_common.h"

#define AUD_MENU "snd/menu.ogg"

static struct {
    char link[MAXSTR];
    char set_file[MAXSTR];
    char map_part[64];
    int  package_id;
    int  downloading;
    int  status_id;
    char progress_label[MAXSTR];
} game_link_ctx;

/*
 * Launch a level or level set once installed.
 */
static int game_link_launch_target(void)
{
    int index;

    set_init();

    if ((index = set_find(game_link_ctx.set_file)) >= 0)
    {
        set_goto(index);

        if (*game_link_ctx.map_part)
        {
            STRBUF sol_basename = str_ends_with(game_link_ctx.map_part, ".sol") ?
                                  strbuf(game_link_ctx.map_part) :
                                  joinstr(game_link_ctx.map_part, ".sol");
            struct level *level = set_find_level(CSTR(sol_basename));

            if (level)
            {
                progress_init(MODE_NORMAL);
                if (progress_play(level))
                    return goto_state(&st_level);
            }
            log_printf("Game Link: level %s not found in set, opening set menu\n", CSTR(sol_basename));
        }

        load_title_background();
        game_kill_fade();
        return goto_state(&st_start);
    }

    log_printf("Game Link: failed to find set %s after installation\n", game_link_ctx.set_file);
    return goto_state(&st_title);
}

/*
 * Progress and completion callbacks for package download.
 */
static void game_link_download_progress(void *data1, void *data2)
{
    struct fetch_progress *pr = data2;

    if (game_link_ctx.status_id)
    {
        char label[MAXSTR];

        if (pr->total > 0)
        {
            int pct = (int) (pr->now * 100.0 / pr->total) % 1000;
            sprintf(label, _("Loading (%d%%)..."), pct);
        }
        else
        {
            SAFECPY(label, _("Loading..."));
        }

        if (strcmp(label, game_link_ctx.progress_label) != 0)
        {
            SAFECPY(game_link_ctx.progress_label, label);
            gui_set_label(game_link_ctx.status_id, label);
        }
    }
}

static void game_link_download_done(void *data1, void *data2)
{
    struct fetch_done *dn = data2;

    game_link_ctx.downloading = 0;

    if (dn && dn->success)
    {
        game_link_launch_target();
    }
    else
    {
        log_printf("Game Link: download failed for package %d\n", game_link_ctx.package_id);
        goto_state(&st_title);
    }
}

static int game_link_start_download(void)
{
    struct fetch_callback callback = { 0 };

    game_link_ctx.downloading = 1;
    SAFECPY(game_link_ctx.progress_label, _("Loading..."));

    callback.progress = game_link_download_progress;
    callback.done = game_link_download_done;
    callback.data = &game_link_ctx;

    if (!package_fetch(game_link_ctx.package_id, callback))
    {
        game_link_download_done(NULL, NULL);
        return 0;
    }

    return 1;
}

static int game_link_action(int tok, int val)
{
    audio_play(AUD_MENU, 1.0f);

    switch (tok)
    {
    case GUI_BACK:
        return exit_state(&st_title);
    }

    return 1;
}

static int game_link_gui(void)
{
    int id;

    if ((id = gui_vstack(0)))
    {
        /* Dimension label box large enough to hold 100% progress. */
        game_link_ctx.status_id = gui_label(id, _("Loading (100%)..."), GUI_SML, gui_wht, gui_wht);

        gui_layout(id, 0, 0);

        gui_set_label(game_link_ctx.status_id, game_link_ctx.progress_label);
    }

    return id;
}

static int game_link_enter(struct state *st, struct state *prev, int intent)
{
    int id;

    common_init(game_link_action);

    SAFECPY(game_link_ctx.progress_label, _("Loading..."));
    id = game_link_gui();

    game_link_start_download();

    return id;
}

static int game_link_leave(struct state *st, struct state *next, int id, int intent)
{
    gui_delete(id);
    return 0;
}

static void game_link_paint(int id, float st)
{
    gui_paint(id);
}

struct state st_game_link = {
    game_link_enter,
    game_link_leave,
    game_link_paint,
    common_timer,
    common_point,
    common_stick,
    NULL,
    common_click,
    common_keybd,
    common_buttn
};

int game_link_handle(const char *link)
{
    if (!(link && *link))
        return 0;

    log_printf("Game Link: handling %s\n", link);

    if (str_starts_with(link, "set-"))
    {
        const size_t prefix_len = strcspn(link, "/");

        STRBUF set_part = substr(link, 0, prefix_len);
        STRBUF map_part = substr(link, prefix_len + 1, 64);
        STRBUF set_file = str_ends_with(CSTR(set_part), ".txt") ?
                          strbuf(CSTR(set_part)) :
                          joinstr(CSTR(set_part), ".txt");

        SAFECPY(game_link_ctx.link, link);
        SAFECPY(game_link_ctx.set_file, CSTR(set_file));
        SAFECPY(game_link_ctx.map_part, CSTR(map_part));

        /* If already installed, launch immediately */
        set_init();
        if (set_find(CSTR(set_file)) >= 0)
        {
            return game_link_launch_target();
        }

        /* Search available packages */
        int pi = package_search(CSTR(set_file));
        if (pi >= 0)
        {
            game_link_ctx.package_id = pi;
            game_link_ctx.downloading = 0;
            SAFECPY(game_link_ctx.progress_label, _("Loading..."));

            goto_state(&st_game_link);
            return 1;
        }

        log_printf("Game Link: set '%s' not found locally or in package catalog\n", CSTR(set_file));
    }

    return 0;
}
