include Makefile

MAPC_TARG= mapc.exe
BALL_TARG= neverball.exe
PUTT_TARG= neverputt.exe

OGL_LIBS := -lm -lopengl32
BASE_LIBS := $(LDFLAGS) -lSDL -lSDL_image -lintl

LIBS := $(SDL_LIBS) -lSDL_image -lSDL_mixer -lSDL_ttf \
	$(OGL_LIBS) $(PNG_LIBS) -lintl

cross:
	$(MAKE) -f Makefile.mingw MAPC_EXEC="wine mapc.exe"
