#-----------------------------------------------------------------------------

EXT= .exe
include Makefile

#-----------------------------------------------------------------------------

WINE= wine

OGL_LIBS= -lm -lopengl32
BASE_LIBS= -lSDL -lSDL_image -lintl

LIBS= \
	$(SDL_LIBS) -lSDL_image -lSDL_mixer -lSDL_ttf \
	$(OGL_LIBS) $(PNG_LIBS) -lintl

#-----------------------------------------------------------------------------

INSTALLER= ../neverball-$(VERSION)-setup.exe

MAKENSIS= makensis
MAKENSIS_FLAGS= -DVERSION=$(VERSION) -DOUTFILE=$(INSTALLER)

TODOS= todos
FROMDOS= fromdos
CP= cp

TEXT_DOCS= \
	doc/AUTHORS \
	doc/MANUAL  \
	CHANGES     \
	COPYING     \
	README

TXT_DOCS= $(TEXT_DOCS:%=%.txt)

#-----------------------------------------------------------------------------

.PHONY: setup
setup: $(INSTALLER)

$(INSTALLER): install-dlls convert-text-files all
	$(MAKENSIS) $(MAKENSIS_FLAGS) -nocd scripts/neverball.nsi

# This fails on MSYS due to a bug in the shipped version of make (3.79.1).
# $(INSTALLER): LDFLAGS += -s
$(INSTALLER): LDFLAGS := $(LDFLAGS) -s

.PHONY: clean-setup
clean-setup: clean
	# $(RM) $(INSTALLER)
	$(RM) install-dlls.sh *.dll $(TXT_DOCS)
	find data -name "*.txt" -exec $(FROMDOS) {} \;

#-----------------------------------------------------------------------------

.PHONY: install-dlls
install-dlls: install-dlls.sh
	sh $<

install-dlls.sh:
	if ! sh scripts/gen-install-dlls.sh > $@; then \
	    $(RM) $@; \
	    exit 1; \
	fi
	@echo --------------------------------------------------------
	@echo You can probably ignore any file-not-found errors above.
	@echo Now edit $@ to your needs before restarting make.
	@echo --------------------------------------------------------
	@exit 1

#-----------------------------------------------------------------------------

.PHONY: convert-text-files
convert-text-files: $(TXT_DOCS)
	find data -name "*.txt" -exec $(TODOS) {} \;

%.txt: %
	$(CP) $< $@
	$(TODOS) $@

#-----------------------------------------------------------------------------

