/*
 * Unit tests for share/solid_all.c and share/solid_vary.c
 *
 * Generated by Antigravity CLI 1.1.22 (Gemini 3.7 Flash (High))
 */

#include "test.h"
#include "solid_all.h"
#include "solid_vary.h"

static void test_sol_body_p_null_base(void)
{
    struct s_base base;
    struct s_vary vary;
    float p[3];

    memset(&base, 0, sizeof (base));
    memset(&vary, 0, sizeof (vary));

    vary.base = &base;

    sol_body_p(p, &vary, 0, 0.0f);

    if (p[0] != 0.0f || p[1] != 0.0f || p[2] != 0.0f)
        exit(1);
}

static void test_sol_body_e_null_base(void)
{
    struct s_base base;
    struct s_vary vary;
    float e[4];

    memset(&base, 0, sizeof (base));
    memset(&vary, 0, sizeof (vary));

    vary.base = &base;

    sol_body_e(e, &vary, 0, 0.0f);

    if (e[0] != 1.0f || e[1] != 0.0f || e[2] != 0.0f || e[3] != 0.0f)
        exit(1);
}

static void test_sol_body_w_null_base(void)
{
    struct s_base base;
    struct s_vary vary;

    memset(&base, 0, sizeof (base));
    memset(&vary, 0, sizeof (vary));

    vary.base = &base;

    if (sol_body_w(&vary, 0) != 0)
        exit(1);
}

static void test_sol_load_vary_oob_path_ref(void)
{
    struct s_base base;
    struct s_vary vary;
    struct b_body body;
    float p[3];

    memset(&base, 0, sizeof (base));
    memset(&body, 0, sizeof (body));

    body.p0 = 0;
    body.p1 = -1;

    base.bc = 1;
    base.bv = &body;
    base.pc = 0;
    base.pv = NULL;

    if (!sol_load_vary(&vary, &base))
        exit(1);

    sol_entity_p(p, &vary, vary.bv[0].mi, vary.bv[0].mj);

    if (p[0] != 0.0f || p[1] != 0.0f || p[2] != 0.0f)
        exit(1);

    sol_free_vary(&vary);
}

int test_solid_all(void)
{
    int pass = 1;

    RUN_TEST("test_sol_body_p_null_base", test_sol_body_p_null_base, pass);
    RUN_TEST("test_sol_body_e_null_base", test_sol_body_e_null_base, pass);
    RUN_TEST("test_sol_body_w_null_base", test_sol_body_w_null_base, pass);
    RUN_TEST("test_sol_load_vary_oob_path_ref", test_sol_load_vary_oob_path_ref, pass);

    return pass;
}
