/*
 * Common unit test harness.
 *
 * Generated by Antigravity CLI 1.1.15 (Gemini 3.7 Flash)
 */

#ifndef TEST_H
#define TEST_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/wait.h>

static inline int run_in_subprocess(void (*test_fn)(void))
{
    fflush(stdout);
    fflush(stderr);

    pid_t pid = fork();
    if (pid == 0)
    {
        int fd = open("/dev/null", O_WRONLY);
        if (fd >= 0)
        {
            dup2(fd, STDOUT_FILENO);
            dup2(fd, STDERR_FILENO);
            close(fd);
        }
        test_fn();
        exit(0);
    }
    else if (pid > 0)
    {
        int status = 0;
        waitpid(pid, &status, 0);
        if (WIFEXITED(status) && WEXITSTATUS(status) == 0)
            return 0;
        if (WIFSIGNALED(status))
            return WTERMSIG(status);
        return -1;
    }
    return -1;
}

#define RUN_TEST(name, fn, pass_var) do { \
    int _res = run_in_subprocess(fn); \
    if (_res == 0) { \
        printf("%s: ok\n", name); \
    } else { \
        printf("%s: FAIL (signal %d)\n", name, _res); \
        (pass_var) = 0; \
    } \
} while (0)

#define RUN_TEST_ASSERT(name, fn, pass_var) do { \
    int _res = run_in_subprocess(fn); \
    if (_res == SIGABRT) { \
        printf("%s: ok\n", name); \
    } else { \
        printf("%s: FAIL (expected abort, got %d)\n", name, _res); \
        (pass_var) = 0; \
    } \
} while (0)

int test_array_all(void);
int test_list_all(void);
int test_queue_all(void);
int test_common_all(void);

#endif
