/*
 * Unit tests for share/queue.c
 *
 * Generated by Antigravity CLI 1.1.15 (Gemini 3.7 Flash)
 */

#include "test.h"
#include "queue.h"

static void test_queue_null_and_empty(void)
{
    Queue q;

    /* NULL queue safety */
    queue_free(NULL);
    if (!queue_empty(NULL))
        exit(1);
    queue_enq(NULL, (void *) 0x1);
    if (queue_deq(NULL) != NULL)
        exit(1);

    /* Normal usage and empty dequeue */
    q = queue_new();
    if (!q)
        exit(1);
    if (!queue_empty(q))
        exit(1);
    if (queue_deq(q) != NULL)
        exit(1);

    queue_enq(q, (void *) 0x42);
    if (queue_empty(q))
        exit(1);
    if (queue_deq(q) != (void *) 0x42)
        exit(1);
    if (!queue_empty(q))
        exit(1);

    queue_free(q);
}

static void test_nonempty_queue_free_asserts(void)
{
    Queue q = queue_new();
    if (!q)
        exit(1);
    queue_enq(q, (void *) 0x42);
    /* Calling queue_free on non-empty queue is a programmer error and must assert */
    queue_free(q);
}

int test_queue_all(void)
{
    int pass = 1;

    RUN_TEST("test_queue_null_and_empty", test_queue_null_and_empty, pass);
    RUN_TEST_ASSERT("test_nonempty_queue_free_asserts", test_nonempty_queue_free_asserts, pass);

    return pass;
}
