/*
 * Unit tests for share/list.c
 *
 * Generated by Antigravity CLI 1.1.15 (Gemini 3.7 Flash)
 */

#include "test.h"
#include "list.h"

static void test_list_null(void)
{
    if (list_rest(NULL) != NULL)
        exit(1);
}

static void test_list_cons_safe_linking(void)
{
    List head = NULL;
    List node;
    char *s1 = strdup("one");
    char *s2 = strdup("two");

    if (!s1 || !s2)
        exit(1);

    node = list_cons(s1, head);
    if (!node)
        exit(1);
    head = node;

    node = list_cons(s2, head);
    if (!node)
        exit(1);
    head = node;

    if (strcmp(head->data, "two") != 0)
        exit(1);
    if (strcmp(head->next->data, "one") != 0)
        exit(1);

    while (head)
    {
        free(head->data);
        head = list_rest(head);
    }
}

static void test_list_push_null_head(void)
{
    int val = 42;
    if (list_push(NULL, &val) != 0)
        exit(1);
}

static void test_list_push_basic(void)
{
    List head = NULL;
    char *s1 = strdup("first");
    char *s2 = strdup("second");
    char *s3 = strdup("third");

    if (!s1 || !s2 || !s3)
        exit(1);

    if (!list_push(&head, s1))
        exit(1);
    if (!list_push(&head, s2))
        exit(1);
    if (!list_push(&head, s3))
        exit(1);

    if (strcmp(head->data, "third") != 0)
        exit(1);
    if (strcmp(head->next->data, "second") != 0)
        exit(1);
    if (strcmp(head->next->next->data, "first") != 0)
        exit(1);
    if (head->next->next->next != NULL)
        exit(1);

    while (head)
    {
        free(head->data);
        head = list_rest(head);
    }
}

int test_list_all(void)
{
    int pass = 1;

    RUN_TEST("test_list_null", test_list_null, pass);
    RUN_TEST("test_list_cons_safe_linking", test_list_cons_safe_linking, pass);
    RUN_TEST("test_list_push_null_head", test_list_push_null_head, pass);
    RUN_TEST("test_list_push_basic", test_list_push_basic, pass);

    return pass;
}
