/*
 * Unit tests for share/array.c
 *
 * Generated by Antigravity CLI 1.1.15 (Gemini 3.7 Flash)
 */

#include "test.h"
#include "array.h"

static void test_null_array_free(void)
{
    array_free(NULL);
}

static void test_null_array_len(void)
{
    int len = array_len(NULL);
    if (len != 0)
        exit(1);
}

static void test_null_array_add(void)
{
    void *p = array_add(NULL);
    if (p != NULL)
        exit(1);
}

static void test_null_array_del(void)
{
    array_del(NULL);
}

static void test_null_array_get(void)
{
    void *p = array_get(NULL, 0);
    if (p != NULL)
        exit(1);
}

static void test_oob_array_get(void)
{
    Array a = array_new(sizeof (int));
    int *val;

    if (!a)
        exit(1);

    val = array_add(a);
    if (val)
        *val = 42;

    if (array_get(a, -1) != NULL)
        exit(1);

    if (array_get(a, 1) != NULL)
        exit(1);

    if (array_get(a, 100) != NULL)
        exit(1);

    array_free(a);
}

static void test_null_alloc(void)
{
    alloc_free(NULL);
    alloc_del(NULL);
    if (alloc_add(NULL) != NULL)
        exit(1);
}

static void test_empty_array_del(void)
{
    Array a = array_new(sizeof (int));
    if (!a)
        exit(1);

    array_del(a);
    if (array_len(a) != 0)
        exit(1);

    array_free(a);
}

static void test_alloc_del_shrink_safety(void)
{
    Array a = array_new(sizeof (int));
    int i;

    if (!a)
        exit(1);

    for (i = 0; i < 100; i++)
    {
        int *val = array_add(a);
        if (!val)
            exit(1);
        *val = i;
    }

    for (i = 0; i < 99; i++)
        array_del(a);

    if (array_len(a) != 1)
        exit(1);

    if (*(int *) array_get(a, 0) != 0)
        exit(1);

    array_free(a);
}

int test_array_all(void)
{
    int pass = 1;

    RUN_TEST("test_null_array_free", test_null_array_free, pass);
    RUN_TEST("test_null_array_len", test_null_array_len, pass);
    RUN_TEST("test_null_array_add", test_null_array_add, pass);
    RUN_TEST("test_null_array_del", test_null_array_del, pass);
    RUN_TEST("test_null_array_get", test_null_array_get, pass);
    RUN_TEST("test_oob_array_get", test_oob_array_get, pass);
    RUN_TEST("test_null_alloc", test_null_alloc, pass);
    RUN_TEST("test_empty_array_del", test_empty_array_del, pass);
    RUN_TEST("test_alloc_del_shrink_safety", test_alloc_del_shrink_safety, pass);

    return pass;
}
