/*
 * Unit tests for ball/level.c (level_title and level_desc)
 *
 * Generated by Antigravity CLI 1.1.22 (Gemini 3.7 Flash (High))
 */

#include "test.h"
#include "level.h"
#include "common.h"
#include "strbuf/strbuf.h"

/* Stubs for unresolved symbols in ball/level.c */

int CONFIG_PLAYER = 0;
struct s_base;
int sol_load_meta(struct s_base *fp, const char *filename) { (void)fp; (void)filename; return 0; }
void sol_free_base(struct s_base *fp) { (void)fp; }
struct level *get_level(int i) { (void)i; return NULL; }
const char *config_get_s(int item) { (void)item; return ""; }
void log_printf(const char *fmt, ...) { (void)fmt; }
void score_init_hs(struct score *s, int timer, int coins) { (void)s; (void)timer; (void)coins; }
void score_time_insert(struct score *s, int *rank, const char *name, int timer, int coins) { (void)s; (void)rank; (void)name; (void)timer; (void)coins; }
void score_coin_insert(struct score *s, int *rank, const char *name, int timer, int coins) { (void)s; (void)rank; (void)name; (void)timer; (void)coins; }

static void test_level_title_standard(void)
{
    struct level l;
    STRBUF t;

    memset(&l, 0, sizeof (l));
    SAFECPY(l.message, "=Buoys=\\He who controls the timers, controls the gates.");

    t = level_title(&l);
    if (strcmp(CSTR(t), "Buoys") != 0)
        exit(1);
}

static void test_level_title_only(void)
{
    struct level l;
    STRBUF t;

    memset(&l, 0, sizeof (l));
    SAFECPY(l.message, "=Buoys=");

    t = level_title(&l);
    if (strcmp(CSTR(t), "Buoys") != 0)
        exit(1);
}

static void test_level_title_newline(void)
{
    struct level l;
    STRBUF t;

    memset(&l, 0, sizeof (l));
    SAFECPY(l.message, "=Buoys=\nDescription line");

    t = level_title(&l);
    if (strcmp(CSTR(t), "Buoys") != 0)
        exit(1);
}

static void test_level_title_untitled(void)
{
    struct level l;
    STRBUF t;

    memset(&l, 0, sizeof (l));
    SAFECPY(l.message, "Mind your footing!");

    t = level_title(&l);
    if (strcmp(CSTR(t), "") != 0)
        exit(1);
}

static void test_level_title_malformed(void)
{
    struct level l;
    STRBUF t;

    memset(&l, 0, sizeof (l));

    SAFECPY(l.message, "=Not closed\\Desc");
    t = level_title(&l);
    if (strcmp(CSTR(t), "") != 0) exit(1);

    SAFECPY(l.message, "==");
    t = level_title(&l);
    if (strcmp(CSTR(t), "") != 0) exit(1);

    SAFECPY(l.message, "=\\");
    t = level_title(&l);
    if (strcmp(CSTR(t), "") != 0) exit(1);

    SAFECPY(l.message, "=Title= extra words\\Desc");
    t = level_title(&l);
    if (strcmp(CSTR(t), "") != 0) exit(1);

    SAFECPY(l.message, "");
    t = level_title(&l);
    if (strcmp(CSTR(t), "") != 0) exit(1);

    t = level_title(NULL);
    if (strcmp(CSTR(t), "") != 0) exit(1);
}

static void test_level_desc_standard(void)
{
    struct level l;
    const char *d;

    memset(&l, 0, sizeof (l));
    SAFECPY(l.message, "=Buoys=\\He who controls the timers, controls the gates.");

    d = level_desc(&l);
    if (strcmp(d, "He who controls the timers, controls the gates.") != 0)
        exit(1);
}

static void test_level_desc_only(void)
{
    struct level l;
    const char *d;

    memset(&l, 0, sizeof (l));
    SAFECPY(l.message, "=Buoys=");

    d = level_desc(&l);
    if (strcmp(d, "") != 0)
        exit(1);
}

static void test_level_desc_untitled(void)
{
    struct level l;
    const char *d;

    memset(&l, 0, sizeof (l));
    SAFECPY(l.message, "Mind your footing!");

    d = level_desc(&l);
    if (strcmp(d, "Mind your footing!") != 0)
        exit(1);
}

static void test_level_desc_newline(void)
{
    struct level l;
    const char *d;

    memset(&l, 0, sizeof (l));
    SAFECPY(l.message, "=Buoys=\r\nLine 1\r\nLine 2");

    d = level_desc(&l);
    if (strcmp(d, "Line 1\r\nLine 2") != 0)
        exit(1);
}

static void test_level_desc_empty_or_null(void)
{
    struct level l;

    memset(&l, 0, sizeof (l));
    SAFECPY(l.message, "");

    if (strcmp(level_desc(&l), "") != 0) exit(1);
    if (strcmp(level_desc(NULL), "") != 0) exit(1);
}

static void test_level_title_extended(void)
{
    struct level l;
    STRBUF t;

    memset(&l, 0, sizeof (l));

    SAFECPY(l.message, "===Ski(ll) Ball Done Right!===\\\\Description");
    t = level_title(&l);
    if (strcmp(CSTR(t), "Ski(ll) Ball Done Right!") != 0) exit(1);
    if (strcmp(level_desc(&l), "Description") != 0) exit(1);

    SAFECPY(l.message, "~~~ Sines ~~~\\\\Well, not precisely");
    t = level_title(&l);
    if (strcmp(CSTR(t), "Sines") != 0) exit(1);
    if (strcmp(level_desc(&l), "Well, not precisely") != 0) exit(1);

    SAFECPY(l.message, ":: Powers of Two :: \\\\Choose your path");
    t = level_title(&l);
    if (strcmp(CSTR(t), "Powers of Two") != 0) exit(1);
    if (strcmp(level_desc(&l), "Choose your path") != 0) exit(1);

    SAFECPY(l.message, "{[(Endurance)]}\\\\Go as far as you want");
    t = level_title(&l);
    if (strcmp(CSTR(t), "Endurance") != 0) exit(1);
    if (strcmp(level_desc(&l), "Go as far as you want") != 0) exit(1);

    SAFECPY(l.message, "<< Tunnel Size Puzzle >>\\\\Blue = Grow");
    t = level_title(&l);
    if (strcmp(CSTR(t), "Tunnel Size Puzzle") != 0) exit(1);
    if (strcmp(level_desc(&l), "Blue = Grow") != 0) exit(1);

    SAFECPY(l.message, "!! Sinking !!\\\\When did I say");
    t = level_title(&l);
    if (strcmp(CSTR(t), "Sinking") != 0) exit(1);
    if (strcmp(level_desc(&l), "When did I say") != 0) exit(1);

    SAFECPY(l.message, "Name: Losing Ground\\\\It is not a bad pun");
    t = level_title(&l);
    if (strcmp(CSTR(t), "Losing Ground") != 0) exit(1);
    if (strcmp(level_desc(&l), "It is not a bad pun") != 0) exit(1);

    SAFECPY(l.message, "Level: Split\\\\A fork in the road");
    t = level_title(&l);
    if (strcmp(CSTR(t), "Split") != 0) exit(1);
    if (strcmp(level_desc(&l), "A fork in the road") != 0) exit(1);
}

int test_level_all(void)
{
    int pass = 1;

    RUN_TEST("test_level_title_standard", test_level_title_standard, pass);
    RUN_TEST("test_level_title_only", test_level_title_only, pass);
    RUN_TEST("test_level_title_newline", test_level_title_newline, pass);
    RUN_TEST("test_level_title_untitled", test_level_title_untitled, pass);
    RUN_TEST("test_level_title_malformed", test_level_title_malformed, pass);
    RUN_TEST("test_level_title_extended", test_level_title_extended, pass);

    RUN_TEST("test_level_desc_standard", test_level_desc_standard, pass);
    RUN_TEST("test_level_desc_only", test_level_desc_only, pass);
    RUN_TEST("test_level_desc_untitled", test_level_desc_untitled, pass);
    RUN_TEST("test_level_desc_newline", test_level_desc_newline, pass);
    RUN_TEST("test_level_desc_empty_or_null", test_level_desc_empty_or_null, pass);

    return pass;
}
