/*
 * Unit test runner for Neverball.
 *
 * Generated by Antigravity CLI 1.1.15 (Gemini 3.7 Flash)
 */

#include "test.h"

int main(void)
{
    int pass = 1;

    if (!test_array_all())
        pass = 0;
    if (!test_list_all())
        pass = 0;
    if (!test_queue_all())
        pass = 0;
    if (!test_common_all())
        pass = 0;
    if (!test_level_all())
        pass = 0;
    if (!test_solid_all())
        pass = 0;

    return pass ? 0 : 1;
}
