/*
 * Unit tests for share/common.c
 *
 * Generated by Antigravity CLI 1.1.15 (Gemini 3.7 Flash)
 */

#include "test.h"
#include "common.h"
#include "fs.h"

/* Stub for fs_gets referenced by common.c read_line */
char *fs_gets(char *buf, int n, fs_file fh)
{
    (void) buf;
    (void) n;
    (void) fh;
    return NULL;
}

static void test_common_read_line_null(void)
{
    if (read_line(NULL, NULL) != 0)
        exit(1);
}

static void test_path_join_null(void)
{
    char *p1 = path_join(NULL, NULL);
    char *p2 = path_join(NULL, "test");
    char *p3 = path_join("test", NULL);

    if (p1 != NULL)
        exit(1);

    if (!p2 || strcmp(p2, "test") != 0)
        exit(1);

    if (!p3 || strcmp(p3, "test") != 0)
        exit(1);

    free(p2);
    free(p3);
}

int test_common_all(void)
{
    int pass = 1;

    RUN_TEST("test_common_read_line_null", test_common_read_line_null, pass);
    RUN_TEST("test_path_join_null", test_path_join_null, pass);

    return pass;
}
