/*
 * Unit tests for share/solid_all.c and share/solid_vary.c
 *
 * Generated by Antigravity CLI 1.1.22 (Gemini 3.7 Flash (High))
 */

#include "test.h"
#include "solid_all.h"
#include "solid_vary.h"

static void test_sol_body_p_null_base(void)
{
    struct s_base base;
    struct s_vary vary;
    float p[3];

    memset(&base, 0, sizeof (base));
    memset(&vary, 0, sizeof (vary));

    vary.base = &base;

    sol_body_p(p, &vary, 0, 0.0f);

    if (p[0] != 0.0f || p[1] != 0.0f || p[2] != 0.0f)
        exit(1);
}

static void test_sol_body_e_null_base(void)
{
    struct s_base base;
    struct s_vary vary;
    float e[4];

    memset(&base, 0, sizeof (base));
    memset(&vary, 0, sizeof (vary));

    vary.base = &base;

    sol_body_e(e, &vary, 0, 0.0f);

    if (e[0] != 1.0f || e[1] != 0.0f || e[2] != 0.0f || e[3] != 0.0f)
        exit(1);
}

static void test_sol_body_w_null_base(void)
{
    struct s_base base;
    struct s_vary vary;

    memset(&base, 0, sizeof (base));
    memset(&vary, 0, sizeof (vary));

    vary.base = &base;

    if (sol_body_w(&vary, 0) != 0)
        exit(1);
}

static void test_sol_load_vary_oob_path_ref(void)
{
    struct s_base base;
    struct s_vary vary;
    struct b_body body;
    float p[3];

    memset(&base, 0, sizeof (base));
    memset(&body, 0, sizeof (body));

    body.p0 = 0;
    body.p1 = -1;

    base.bc = 1;
    base.bv = &body;
    base.pc = 0;
    base.pv = NULL;

    if (!sol_load_vary(&vary, &base))
        exit(1);

    sol_entity_p(p, &vary, vary.bv[0].mi, vary.bv[0].mj);

    if (p[0] != 0.0f || p[1] != 0.0f || p[2] != 0.0f)
        exit(1);

    sol_free_vary(&vary);
}

#include <math.h>

static int vec3_approx(const float a[3], float x, float y, float z)
{
    return fabsf(a[0] - x) < 0.001f &&
           fabsf(a[1] - y) < 0.001f &&
           fabsf(a[2] - z) < 0.001f;
}

static void test_sol_mover_parent_first_eval(void)
{
    struct s_base base;
    struct s_vary vary;
    struct b_path paths[3];
    struct b_body bodies[2];
    float p[3];

    memset(&base, 0, sizeof (base));
    memset(&vary, 0, sizeof (vary));
    memset(paths, 0, sizeof (paths));
    memset(bodies, 0, sizeof (bodies));

    /* Path 0: parent segment start, active */
    paths[0].p[0] = 0.0f;
    paths[0].p[1] = 0.0f;
    paths[0].p[2] = 0.0f;
    paths[0].e[0] = 1.0f;
    paths[0].t    = 1.0f;
    paths[0].tm   = 1000;
    paths[0].pi   = 1;
    paths[0].f    = 1;
    paths[0].p0   = -1;
    paths[0].p1   = -1;

    /* Path 1: parent segment end, loops back */
    paths[1].p[0] = 10.0f;
    paths[1].p[1] = 0.0f;
    paths[1].p[2] = 0.0f;
    paths[1].e[0] = 1.0f;
    paths[1].t    = 1.0f;
    paths[1].tm   = 1000;
    paths[1].pi   = 0;
    paths[1].f    = 1;
    paths[1].p0   = -1;
    paths[1].p1   = -1;

    /* Path 2: child node offset at (0, 5, 0), attached to Path 0, inactive */
    paths[2].p[0] = 0.0f;
    paths[2].p[1] = 5.0f;
    paths[2].p[2] = 0.0f;
    paths[2].e[0] = 1.0f;
    paths[2].t    = 1.0f;
    paths[2].tm   = 1000;
    paths[2].pi   = 2;
    paths[2].f    = 0;
    paths[2].p0   = 0;
    paths[2].p1   = -1;

    bodies[0].p0 = 0;
    bodies[0].p1 = -1;
    bodies[1].p0 = 2;
    bodies[1].p1 = -1;

    base.pc = 3;
    base.pv = paths;
    base.bc = 2;
    base.bv = bodies;

    if (!sol_load_vary(&vary, &base))
        exit(1);

    /* Initial evaluation at t = 0 */
    sol_body_p(p, &vary, vary.bv[0].mi, 0.0f);
    if (!vec3_approx(p, 0.0f, 0.0f, 0.0f))
        exit(1);

    sol_body_p(p, &vary, vary.bv[1].mi, 0.0f);
    if (!vec3_approx(p, 0.0f, 5.0f, 0.0f))
        exit(1);

    /* Advance simulation by 0.5s (parent moves to X=5) */
    sol_move_step(&vary, NULL, 0.5f, 500);

    /* Evaluate parent first (clearing parent's dirty flag) */
    sol_body_p(p, &vary, vary.bv[0].mi, 0.0f);
    if (!vec3_approx(p, 5.0f, 0.0f, 0.0f))
        exit(1);

    /* Evaluate child second: child world position must follow parent to X=5, Y=5 */
    sol_body_p(p, &vary, vary.bv[1].mi, 0.0f);
    if (!vec3_approx(p, 5.0f, 5.0f, 0.0f))
        exit(1);

    sol_free_vary(&vary);
}

static void test_sol_mover_child_first_eval(void)
{
    struct s_base base;
    struct s_vary vary;
    struct b_path paths[3];
    struct b_body bodies[2];
    float p[3];

    memset(&base, 0, sizeof (base));
    memset(&vary, 0, sizeof (vary));
    memset(paths, 0, sizeof (paths));
    memset(bodies, 0, sizeof (bodies));

    paths[0].p[0] = 0.0f;
    paths[0].p[1] = 0.0f;
    paths[0].p[2] = 0.0f;
    paths[0].e[0] = 1.0f;
    paths[0].t    = 1.0f;
    paths[0].tm   = 1000;
    paths[0].pi   = 1;
    paths[0].f    = 1;
    paths[0].p0   = -1;
    paths[0].p1   = -1;

    paths[1].p[0] = 10.0f;
    paths[1].p[1] = 0.0f;
    paths[1].p[2] = 0.0f;
    paths[1].e[0] = 1.0f;
    paths[1].t    = 1.0f;
    paths[1].tm   = 1000;
    paths[1].pi   = 0;
    paths[1].f    = 1;
    paths[1].p0   = -1;
    paths[1].p1   = -1;

    paths[2].p[0] = 0.0f;
    paths[2].p[1] = 5.0f;
    paths[2].p[2] = 0.0f;
    paths[2].e[0] = 1.0f;
    paths[2].t    = 1.0f;
    paths[2].tm   = 1000;
    paths[2].pi   = 2;
    paths[2].f    = 0;
    paths[2].p0   = 0;
    paths[2].p1   = -1;

    bodies[0].p0 = 0;
    bodies[0].p1 = -1;
    bodies[1].p0 = 2;
    bodies[1].p1 = -1;

    base.pc = 3;
    base.pv = paths;
    base.bc = 2;
    base.bv = bodies;

    if (!sol_load_vary(&vary, &base))
        exit(1);

    sol_body_p(p, &vary, vary.bv[0].mi, 0.0f);
    sol_body_p(p, &vary, vary.bv[1].mi, 0.0f);

    sol_move_step(&vary, NULL, 0.5f, 500);

    /* Evaluate child FIRST: should trigger parent evaluation and return X=5, Y=5 */
    sol_body_p(p, &vary, vary.bv[1].mi, 0.0f);
    if (!vec3_approx(p, 5.0f, 5.0f, 0.0f))
        exit(1);

    /* Evaluate parent SECOND: should be a clean cache hit at X=5, Y=0 */
    sol_body_p(p, &vary, vary.bv[0].mi, 0.0f);
    if (!vec3_approx(p, 5.0f, 0.0f, 0.0f))
        exit(1);

    sol_free_vary(&vary);
}

static void test_sol_mover_multi_children(void)
{
    struct s_base base;
    struct s_vary vary;
    struct b_path paths[4];
    struct b_body bodies[3];
    float p[3];

    memset(&base, 0, sizeof (base));
    memset(&vary, 0, sizeof (vary));
    memset(paths, 0, sizeof (paths));
    memset(bodies, 0, sizeof (bodies));

    /* Parent moving along X */
    paths[0].e[0] = 1.0f;
    paths[0].t    = 1.0f;
    paths[0].tm   = 1000;
    paths[0].pi   = 1;
    paths[0].f    = 1;
    paths[0].p0   = -1;
    paths[0].p1   = -1;

    paths[1].p[0] = 10.0f;
    paths[1].e[0] = 1.0f;
    paths[1].t    = 1.0f;
    paths[1].tm   = 1000;
    paths[1].pi   = 0;
    paths[1].f    = 1;
    paths[1].p0   = -1;
    paths[1].p1   = -1;

    /* Child 1 offset at (0, 5, 0), attached to Path 0 */
    paths[2].p[1] = 5.0f;
    paths[2].e[0] = 1.0f;
    paths[2].t    = 1.0f;
    paths[2].tm   = 1000;
    paths[2].pi   = 2;
    paths[2].f    = 0;
    paths[2].p0   = 0;
    paths[2].p1   = -1;

    /* Child 2 offset at (0, -5, 0), attached to Path 0 */
    paths[3].p[1] = -5.0f;
    paths[3].e[0] = 1.0f;
    paths[3].t    = 1.0f;
    paths[3].tm   = 1000;
    paths[3].pi   = 3;
    paths[3].f    = 0;
    paths[3].p0   = 0;
    paths[3].p1   = -1;

    bodies[0].p0 = 0;
    bodies[0].p1 = -1;
    bodies[1].p0 = 2;
    bodies[1].p1 = -1;
    bodies[2].p0 = 3;
    bodies[2].p1 = -1;

    base.pc = 4;
    base.pv = paths;
    base.bc = 3;
    base.bv = bodies;

    if (!sol_load_vary(&vary, &base))
        exit(1);

    sol_body_p(p, &vary, vary.bv[0].mi, 0.0f);
    sol_body_p(p, &vary, vary.bv[1].mi, 0.0f);
    sol_body_p(p, &vary, vary.bv[2].mi, 0.0f);

    sol_move_step(&vary, NULL, 0.5f, 500);

    /* Evaluate Parent -> Child 1 -> Child 2 */
    sol_body_p(p, &vary, vary.bv[0].mi, 0.0f);
    if (!vec3_approx(p, 5.0f, 0.0f, 0.0f))
        exit(1);

    sol_body_p(p, &vary, vary.bv[1].mi, 0.0f);
    if (!vec3_approx(p, 5.0f, 5.0f, 0.0f))
        exit(1);

    sol_body_p(p, &vary, vary.bv[2].mi, 0.0f);
    if (!vec3_approx(p, 5.0f, -5.0f, 0.0f))
        exit(1);

    sol_free_vary(&vary);
}

static void test_sol_mover_multilevel_hierarchy(void)
{
    struct s_base base;
    struct s_vary vary;
    struct b_path paths[5];
    struct b_body bodies[3];
    float p[3];

    memset(&base, 0, sizeof (base));
    memset(&vary, 0, sizeof (vary));
    memset(paths, 0, sizeof (paths));
    memset(bodies, 0, sizeof (bodies));

    /* Mover A: moves along X from 0 to 10 */
    paths[0].e[0] = 1.0f;
    paths[0].t    = 1.0f;
    paths[0].tm   = 1000;
    paths[0].pi   = 1;
    paths[0].f    = 1;
    paths[0].p0   = -1;
    paths[0].p1   = -1;

    paths[1].p[0] = 10.0f;
    paths[1].e[0] = 1.0f;
    paths[1].t    = 1.0f;
    paths[1].tm   = 1000;
    paths[1].pi   = 0;
    paths[1].f    = 1;
    paths[1].p0   = -1;
    paths[1].p1   = -1;

    /* Mover B: attached to Path 0, moves along Y from 0 to 10 */
    paths[2].e[0] = 1.0f;
    paths[2].t    = 1.0f;
    paths[2].tm   = 1000;
    paths[2].pi   = 3;
    paths[2].f    = 1;
    paths[2].p0   = 0;
    paths[2].p1   = -1;

    paths[3].p[1] = 10.0f;
    paths[3].e[0] = 1.0f;
    paths[3].t    = 1.0f;
    paths[3].tm   = 1000;
    paths[3].pi   = 2;
    paths[3].f    = 1;
    paths[3].p0   = 0;
    paths[3].p1   = -1;

    /* Mover C: attached to Path 2, inactive, offset at Z=5 */
    paths[4].p[2] = 5.0f;
    paths[4].e[0] = 1.0f;
    paths[4].t    = 1.0f;
    paths[4].tm   = 1000;
    paths[4].pi   = 4;
    paths[4].f    = 0;
    paths[4].p0   = 2;
    paths[4].p1   = -1;

    bodies[0].p0 = 0;
    bodies[0].p1 = -1;
    bodies[1].p0 = 2;
    bodies[1].p1 = -1;
    bodies[2].p0 = 4;
    bodies[2].p1 = -1;

    base.pc = 5;
    base.pv = paths;
    base.bc = 3;
    base.bv = bodies;

    if (!sol_load_vary(&vary, &base))
        exit(1);

    sol_body_p(p, &vary, vary.bv[0].mi, 0.0f);
    sol_body_p(p, &vary, vary.bv[1].mi, 0.0f);
    sol_body_p(p, &vary, vary.bv[2].mi, 0.0f);

    sol_move_step(&vary, NULL, 0.5f, 500);

    /* Root-to-leaf evaluation: A -> B -> C */
    sol_body_p(p, &vary, vary.bv[0].mi, 0.0f);
    if (!vec3_approx(p, 5.0f, 0.0f, 0.0f))
        exit(1);

    sol_body_p(p, &vary, vary.bv[1].mi, 0.0f);
    if (!vec3_approx(p, 5.0f, 5.0f, 0.0f))
        exit(1);

    sol_body_p(p, &vary, vary.bv[2].mi, 0.0f);
    if (!vec3_approx(p, 5.0f, 5.0f, 5.0f))
        exit(1);

    sol_free_vary(&vary);
}

static void test_sol_mover_split_node_parents(void)
{
    struct s_base base;
    struct s_vary vary;
    struct b_path paths[4];
    struct b_body bodies[2];
    float p[3];

    memset(&base, 0, sizeof (base));
    memset(&vary, 0, sizeof (vary));
    memset(paths, 0, sizeof (paths));
    memset(bodies, 0, sizeof (bodies));

    /* Node 0: unparented (static ground), starts at (0, 0, 0), inactive */
    paths[0].e[0] = 1.0f;
    paths[0].t    = 1.0f;
    paths[0].tm   = 1000;
    paths[0].pi   = 1;
    paths[0].f    = 0;
    paths[0].p0   = -1;
    paths[0].p1   = -1;

    /* Node 1: attached to moving Platform (Path 2), local offset (0, 0, 0) */
    paths[1].e[0] = 1.0f;
    paths[1].t    = 1.0f;
    paths[1].tm   = 1000;
    paths[1].pi   = 0;
    paths[1].f    = 0;
    paths[1].p0   = 2;
    paths[1].p1   = -1;


    /* Platform (Path 2 -> 3): moves along X from 0 to 10 */
    paths[2].e[0] = 1.0f;
    paths[2].t    = 1.0f;
    paths[2].tm   = 1000;
    paths[2].pi   = 3;
    paths[2].f    = 1;
    paths[2].p0   = -1;
    paths[2].p1   = -1;

    paths[3].p[0] = 10.0f;
    paths[3].e[0] = 1.0f;
    paths[3].t    = 1.0f;
    paths[3].tm   = 1000;
    paths[3].pi   = 2;
    paths[3].f    = 1;
    paths[3].p0   = -1;
    paths[3].p1   = -1;

    /* Body 0: Platform (Path 2) */
    bodies[0].p0 = 2;
    bodies[0].p1 = -1;

    /* Body 1: Traversing Node 0 -> Node 1 */
    bodies[1].p0 = 0;
    bodies[1].p1 = -1;

    base.pc = 4;
    base.pv = paths;
    base.bc = 2;
    base.bv = bodies;

    if (!sol_load_vary(&vary, &base))
        exit(1);

    /* Body 1 is stationary halfway along segment 0 -> 1 */
    vary.mv[vary.bv[1].mi].t = 0.5f;

    /* Initial eval */
    sol_body_p(p, &vary, vary.bv[0].mi, 0.0f);
    sol_body_p(p, &vary, vary.bv[1].mi, 0.0f);
    if (!vec3_approx(p, 0.0f, 0.0f, 0.0f))
        exit(1);

    sol_move_step(&vary, NULL, 0.5f, 500);


    /* Platform moved to X=5.
     * Body 1 is at t=0.5 between Node 0 (static 0,0,0) and Node 1 (moving with platform at 5,0,0).
     * Body 1's position must be halfway: X = 2.5!
     */
    sol_body_p(p, &vary, vary.bv[0].mi, 0.0f);
    if (!vec3_approx(p, 5.0f, 0.0f, 0.0f))
        exit(1);

    sol_body_p(p, &vary, vary.bv[1].mi, 0.0f);
    if (!vec3_approx(p, 2.5f, 0.0f, 0.0f))
        exit(1);

    sol_free_vary(&vary);
}

static void test_sol_mover_rotation_parent(void)
{
    struct s_base base;
    struct s_vary vary;
    struct b_path paths[3];
    struct b_body bodies[2];
    float p[3];

    memset(&base, 0, sizeof (base));
    memset(&vary, 0, sizeof (vary));
    memset(paths, 0, sizeof (paths));
    memset(bodies, 0, sizeof (bodies));

    /* Node 0: platform start rotation (identity) */
    paths[0].e[0] = 1.0f;
    paths[0].t    = 1.0f;
    paths[0].tm   = 1000;
    paths[0].pi   = 1;
    paths[0].f    = 1;
    paths[0].p0   = -1;
    paths[0].p1   = -1;

    /* Node 1: platform 180 deg rotation about Z: e = (0, 0, 0, 1) */
    paths[1].e[0] = 0.0f;
    paths[1].e[3] = 1.0f;
    paths[1].t    = 1.0f;
    paths[1].tm   = 1000;
    paths[1].pi   = 0;
    paths[1].f    = 1;
    paths[1].p0   = -1;
    paths[1].p1   = -1;

    /* Node 2: child at offset (5, 0, 0), attached to Platform's rotation (p1 = 0) */
    paths[2].p[0] = 5.0f;
    paths[2].e[0] = 1.0f;
    paths[2].t    = 1.0f;
    paths[2].tm   = 1000;
    paths[2].pi   = 2;
    paths[2].f    = 0;
    paths[2].p0   = -1;
    paths[2].p1   = 0;

    /* Body 0: Platform rotation */
    bodies[0].p0 = -1;
    bodies[0].p1 = 0;

    /* Body 1: Child attached to Platform */
    bodies[1].p0 = 2;
    bodies[1].p1 = -1;

    base.pc = 3;
    base.pv = paths;
    base.bc = 2;
    base.bv = bodies;

    if (!sol_load_vary(&vary, &base))
        exit(1);

    /* Initial eval: child is at (5, 0, 0) */
    sol_body_p(p, &vary, vary.bv[0].mi, 0.0f);
    sol_body_p(p, &vary, vary.bv[1].mi, 0.0f);
    if (!vec3_approx(p, 5.0f, 0.0f, 0.0f))
        exit(1);

    /* Advance 0.5s: Platform rotates 90 deg about Z. Child (5, 0, 0) rotates to (0, 5, 0) */
    sol_move_step(&vary, NULL, 0.5f, 500);

    /* Evaluate Platform rotation first (clearing its dirty flag) */
    float e[4];
    sol_body_e(e, &vary, vary.bv[0].mj, 0.0f);

    /* Evaluate Child second: must be rotated to (0, 5, 0) */
    sol_body_p(p, &vary, vary.bv[1].mi, 0.0f);
    if (!vec3_approx(p, 0.0f, 5.0f, 0.0f))
        exit(1);


    sol_free_vary(&vary);
}

int test_solid_all(void)
{
    int pass = 1;

    RUN_TEST("test_sol_body_p_null_base", test_sol_body_p_null_base, pass);
    RUN_TEST("test_sol_body_e_null_base", test_sol_body_e_null_base, pass);
    RUN_TEST("test_sol_body_w_null_base", test_sol_body_w_null_base, pass);
    RUN_TEST("test_sol_load_vary_oob_path_ref", test_sol_load_vary_oob_path_ref, pass);
    RUN_TEST("test_sol_mover_parent_first_eval", test_sol_mover_parent_first_eval, pass);
    RUN_TEST("test_sol_mover_child_first_eval", test_sol_mover_child_first_eval, pass);
    RUN_TEST("test_sol_mover_multi_children", test_sol_mover_multi_children, pass);
    RUN_TEST("test_sol_mover_multilevel_hierarchy", test_sol_mover_multilevel_hierarchy, pass);
    RUN_TEST("test_sol_mover_split_node_parents", test_sol_mover_split_node_parents, pass);
    RUN_TEST("test_sol_mover_rotation_parent", test_sol_mover_rotation_parent, pass);

    return pass;
}



