.TH MAPC 1 "April 11, 2004"
.SH NAME
mapc \- A map compiler for neverball and neverputt game
.SH SYNOPSIS
\fBmapc\fR \fIsource.map\fR \fItarget.sol\fR \fIdatadir\fR
.br
.SH DESCRIPTION
\fBmapc\fR is a map compiler for neverball and neverputt game.
.SH OPTIONS
See the synopsis.
.SH AUTHOR
This manual page was written by Tamas SZERB <toma@rulez.org>
