.TH NEVERPUTT 6 "April 11, 2004"
.SH NAME
neverputt \- A 3D mini golf game
.SH SYNOPSIS
\fBneverputt\fR \fI[<datadir>]\fR
.br
.SH DESCRIPTION
Based on the physics and graphics of Neverball, Neverputt is a hot-seat
multi-player miniature golf game for 1 to 4 players. The 18-hole course
takes advantage of all the elements that challenge Neverball players,
including moving platforms and barriers, teleporters, ramps, and drop-offs.
A simple putting interface and golf scoring system have been added.
.SH OPTIONS
The following command-line options are available:
.TP
.B [<datadir>]
Run the game with a different data directory
.SH AUTHOR
This manual page was written by Tamas SZERB <toma@rulez.org>.
