
sol/%.sol : map/%.map
	../mapc $< $@

all : 	sol/easy.sol \
	sol/fall.sol \
	sol/move.sol \
	sol/maze.sol \
	sol/four.sol \
	sol/poke.sol \
	sol/angle.sol \
	sol/quads.sol \
	sol/spiral.sol \
	sol/marble.sol

clean :
	rm -f map/*.bak
	rm -f sol/*.sol
