
all :
	(cd libvec;  $(MAKE))
	(cd libaio;  $(MAKE))
	(cd libsol;  $(MAKE))
	(cd libglw;  $(MAKE))
	(cd ball;    $(MAKE))
	(cd map2sol; $(MAKE))

install :
	(cd libvec;  $(MAKE) install)
	(cd libaio;  $(MAKE) install)
	(cd libsol;  $(MAKE) install)
	(cd libglw;  $(MAKE) install)
	(cd ball;    $(MAKE) install)
	(cd map2sol; $(MAKE) install)

clean :
	(cd libvec;  $(MAKE) clean)
	(cd libaio;  $(MAKE) clean)
	(cd libsol;  $(MAKE) clean)
	(cd libglw;  $(MAKE) clean)
	(cd ball;    $(MAKE) clean)
	(cd map2sol; $(MAKE) clean)

